// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader {
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String, dynamic> ar = {
    "signup_button": "تسجيل جديد",
    "login_button": "تسجيل دخول",
    "login_title": "دعنا نسجل دخولك",
    "login_subtitle": "مرحبًا بك مرة أخرى ، لقد فاتتك!",
    "forget_password": "نسيت كلمة المرور ؟",
    "login_google": "الاستمرار بجوجل",
    "guest": "الاستمرار كزائر",
    "not_have_account": "ليس لديك حساب ؟ ",
    "password": "كلمة المرور",
    "email": "البريد الالكتروني",
    "reset_pass": "إعادة تعيين كلمة المرور",
    "password_title":
        "أدخل بريدك الإلكتروني لإعادة تعيين كلمة المرور الخاصة بك",
    "reset_pass_button": "إعادة ضبط",
    "create_account": "انشاء حساب للاستمرار",
    "have_account": "لديك حساب ؟ ",
    "sign_in": "تسجيل دخول",
    "sign_up": "تسجيل حساب",
    "get_start": "ابدء",
    "confirm_pass": "تاكيد كلمة المرور",
    "person_info": "معلوماتك الشخصية",
    "fill_in": "املأ معلوماتك الشخصية للمتابعة!",
    "full_name": "الاسم بالكامل",
    "phone": "رقم الهاتف",
    "birth_date": "تاريخ الميلاد",
    "gender": "الجنس",
    "male": "ذكر",
    "female": "انثي",
    "finish": "انهاء",
    "booking": "الحجز",
    "store": "المتجر",
    "memberShip": "عضوية",
    "points": "عروض النقاط",
    "date": "التاريخ",
    "time": "الوقت",
    "filter": "تصفية",
    "sort": "تصنيف",
    "add": "اضف",
    "total": "الاجمالي",
    "checkout": "الدفع",
    "confirm": "تاكيد",
    "cash": "نقدي",
    "visa": "دفع اونلاين",
    "payment_type": "خيارات الدفع",
    "hi": "مرحبا",
    "notifications": "الاشعارات",
    "raward": "المكافآت",
    "book_history": "سجل الحجز",
    "orders_history": "تاريخ الطلبات",
    "about": "معلومات عنا",
    "high_price": "السعر من الارخص للاعلى",
    "low_price": "السعر الاعلى الى الادنى",
    "appl": "APPLY",
    "indoor": "في الداخل",
    "outdoor": "في الخارج",
    "result": "النتائج",
    "type": "نوع",
    "interval": "المدة",
    "time_range": "Time Range"
  };
  static const Map<String, dynamic> en = {
    "signup_button": "Sign Up",
    "login_button": "SIGN IN",
    "not_have_account": "Don't have an account ? ",
    "login_title": "Let's Sign You In ",
    "login_subtitle": "Welcome back you'v been missed!",
    "forget_password": "Forgot your Password ? ",
    "login_google": "Continue with Google",
    "guest": "Continue as a Guest",
    "country_code": "conutry code",
    "password": "password",
    "email": "Email",
    "reset_pass": "Reset Password",
    "password_title": "Enter your Email to reset your password",
    "reset_pass_button": "RESET",
    "create_account": "Create an Account to continue",
    "have_account": "Already have an Account ?  ",
    "sign_in": "Sign In",
    "sign_up": "SIGN UP",
    "get_start": "Getting Started",
    "confirm_pass": "Confirm Password",
    "person_info": "Personal Info",
    "fill_in": "Fill in your personal information to continue!",
    "full_name": "Full Name",
    "phone": "Phone number",
    "birth_date": "Date of Birth",
    "gender": "Gender",
    "male": "Male",
    "female": "Female",
    "finish": "Finish",
    "booking": "Booking",
    "store": "Store",
    "memberShip": "Membership",
    "points": "Points offers",
    "date": "Date",
    "time": "Time",
    "filter": "Filter",
    "sort": "Sort",
    "add": "Add",
    "total": "Total",
    "checkout": "CHECKOUT",
    "confirm": "CONFIRM",
    "cash": "Cash",
    "visa": "Visa",
    "payment_type": "Payment Options",
    "hi": "Hi,",
    "notifications": "Notifications",
    "raward": "Rewards",
    "book_history": "Booking History",
    "orders_history": "Orders History",
    "about": "About us",
    "high_price": "Price Low to High",
    "low_price": "Price High to Low",
    "appl": "APPLY",
    "indoor": "Indoor",
    "outdoor": "Outdoor",
    "result": "RESULT",
    "type": "Type",
    "interval": "Interval",
    "time_range": "Time Range"
  };

  static const Map<String, Map<String, dynamic>> mapLocales = {
    "en": en,
    "ar": ar,
  };
}
